const SALE_ITEMS=[
{cat:"Furniture",name:"Kitchen Table + Chairs",desc:"Solid dining set, seats 4-6. Great condition."},
{cat:"Furniture",name:"Ant Dinner Table + 3 Chairs",desc:"Stylish Ant-style drop-leaf dining table with 3 matching chairs. Oak veneer with fabric seats. Extends from square to round — seats 2-4. Great condition."},
{cat:"Furniture",name:"Coffee Table + China Cabinet",desc:"Matching set, perfect for a living room."},
{cat:"Furniture",name:"TV Stand",desc:"Sturdy entertainment unit with shelving."},
{cat:"Furniture",name:"Lounge Chairs",desc:"Comfortable lounge seating."},
{cat:"Furniture",name:"Beds",desc:"Bed frames — enquire for sizes available."},
{cat:"Furniture",name:"Chest of Drawers + Side Table",desc:"Bedroom storage set."},
{cat:"Furniture",name:"2nd Chest of Drawers",desc:"Additional chest of drawers, good condition."},
{cat:"Furniture",name:"Antique Chair",desc:"Beautiful vintage piece with character."},
{cat:"Furniture",name:"Work Desk + Chair",desc:"Home office desk and ergonomic chair."},
{cat:"Appliances",name:"Samsung 500L Twin Cooling Plus Fridge",desc:"Samsung 500L Twin Cooling Plus fridge in black. Dual cooling system keeps fridge and freezer at independent temperatures. 14 years old and still running perfectly — no issues at all. Great size for a family. Must go — moving overseas!"},
{cat:"Appliances",name:"Microwave",desc:"Standard microwave, good working order."},
{cat:"Appliances",name:"Washing Machine",desc:"Front/top loader — works great."},
{cat:"Appliances",name:"Dryer",desc:"Clothes dryer, fully functional."},
{cat:"Appliances",name:"Iron + Ironing Board",desc:"Iron and full-size ironing board."},
{cat:"Appliances",name:"Heater",desc:"Electric heater for cooler months."},
{cat:"Appliances",name:"Toaster",desc:"Standard toaster, good condition."},
{cat:"Appliances",name:"Kettle",desc:"Electric kettle."},
{cat:"Appliances",name:"Blender",desc:"Kitchen blender, works perfectly."},
{cat:"Appliances",name:"Vacuum Cleaner",desc:"Vacuum cleaner with attachments."},
{cat:"Kitchen",name:"Pots & Pans",desc:"Assorted cookware set."},
{cat:"Kitchen",name:"Cutlery Set",desc:"Full cutlery set for the household."},
{cat:"Kitchen",name:"Dinner Set (Plates/Bowls)",desc:"Complete dinner set with plates and bowls."},
{cat:"Kitchen",name:"Glasses & Mugs",desc:"Drinking glasses and coffee mugs."},
{cat:"Kitchen",name:"Baking Trays & Dishes",desc:"Oven trays and baking dishes."},
{cat:"Kitchen",name:"Chopping Boards",desc:"Wooden and plastic chopping boards."},
{cat:"Kitchen",name:"Utensils",desc:"Cooking utensils — spatulas, tongs, spoons, etc."},
{cat:"Kitchen",name:"Food Storage Containers",desc:"Assorted Tupperware-style containers."},
{cat:"Electronics",name:"TV",desc:"Television — enquire for size and brand."},
{cat:"Electronics",name:"Monitors",desc:"Computer monitors, great for work or gaming."},
{cat:"Electronics",name:"Stereo",desc:"Sound system / stereo setup."},
{cat:"Electronics",name:"Car",desc:"Vehicle for sale — enquire for details."},
{cat:"Bedroom/Bathroom",name:"3x Lamps",desc:"Set of three lamps — bedside and floor."},
{cat:"Bedroom/Bathroom",name:"Bedding (sheets/pillows/doonas)",desc:"Sheets, pillows, and doonas — assorted."},
{cat:"Bedroom/Bathroom",name:"Towels",desc:"Bath and hand towels."},
{cat:"Bedroom/Bathroom",name:"Mirrors",desc:"Wall and standing mirrors."},
{cat:"Misc",name:"Plasma Cutter",desc:"Plasma cutting tool — great for metalwork."},
{cat:"Misc",name:"Garden Tools",desc:"Shovels, rakes, pruners, and more."},
{cat:"Misc",name:"Outdoor Furniture",desc:"Patio/outdoor setting."},
{cat:"Misc",name:"BBQ",desc:"Barbecue — ready for summer."},
{cat:"Misc",name:"Eskys/Coolers",desc:"Coolers and eskys, assorted sizes."},
{cat:"Misc",name:"Monopoly Set + Board Games",desc:"Classic board games collection."},
{cat:"Misc",name:"Paintings",desc:"Wall art and paintings."},
{cat:"Misc",name:"Coin Collection",desc:"Collectible coins — enquire for details."},
{cat:"Misc",name:"Curtains/Blinds",desc:"Window coverings, various sizes."},
{cat:"Misc",name:"Rugs",desc:"Floor rugs, assorted styles."},
{cat:"Misc",name:"Bookshelf + Books",desc:"Bookshelf with a collection of books."},
{cat:"Misc",name:"Luggage",desc:"Suitcases and travel bags."},
{cat:"Car",name:"Car",desc:"Details coming soon — enquire for info."}
];
const SALE_CATEGORIES=["All","Furniture","Appliances","Kitchen","Electronics","Bedroom/Bathroom","Misc","Car","Misc"];
if(typeof module!=='undefined')module.exports={SALE_ITEMS,SALE_CATEGORIES};
